# Database Configuration
db.url=jdbc:mysql://localhost:3306/customorm_demo
db.username=root
db.password=pratham@2005
db.driver=com.mysql.cj.jdbc.Driver

# ORM Configuration
orm.show.sql=true
orm.format.sql=true